name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.json
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
